### ISSUE TITLE
Why?

### ISSUE THREAD

**Issue by grantcarthew** [egoist/puex#2]

**Comment by LinusBorg** [comment]
Different Size vs. feature-set tradeoff for different needs.

**Comment by willwillems** [comment]
It would be very useful in my opinion to add some sort of comparison with vuex + the goals of puex in the README.md.

**Comment by officert** [comment]
Do you need to use this with Vuex or can it be used stand alone?

**Comment by LinusBorg** [comment]
Standalone.

**Comment by DrSensor** [comment]
I'm confused. In readme it says
```
Dropped unnecessary features (for specific use cases).
```

What list of features is being dropped?

**Comment by egoist** [comment]
@DrSensor A LOT, see https://github.com/egoist/puex#api

**Comment by egoist** [comment]
The main differences:

- puex is smaller
- puex has fewer features (which also means, simpler 😅)
- `mapXXX()` helpers are also available on puex `store` instance
- `puex` does not have `vue-devtools` support

**Comment by DrSensor** [comment]
Ah I see, thank you. I also notice based on readme action and mutation can be bypassed using `replaceState`. Also state now accept `Function` to.

Because state now can accept anything, can state also store VNode and/or normal Node?

**Comment by egoist** [comment]
FYI, just added vue-devtools support thanks to @psi-4ward
